### ISSUE TITLE
HMR doesn't work for pages if all scripts are commented out

### ISSUE THREAD

**Issue by rohit-gohri** [webdiscus/html-bundler-webpack-plugin#11]
## Current behaviour

If a page doesn't have any script tags then HMR doesn't load always even though the build output shows that hot-update.js file has been added to assets.

## Expected behaviour

HMR should work by adding the empty js file. But it is not added to all pages.

### Reproduction Example

This repo https://github.com/rohit-gohri/html-bundler-webpack-plugin-hmr-issue created from the boilerplate and modified to remove scripts from the template has the `/demo.html` page no longer hot-reloading on changes.

## Environment

- OS: macOS
- version of Node.js: 16
- version of Webpack: 5
- version of the Plugin: 1.17.1

## Additional context

If I remove this `!hasScript` condition in my node _modules then it works:
https://github.com/webdiscus/html-bundler-webpack-plugin/blob/ac5c966632f7bce2d2aa501ae3332fdb145108bb/src/Loader/Modes/RenderMode.js#L111

**Comment by webdiscus** [comment]
Hallo @rohit-gohri,

thanks for the issue report.
I try to fix it.

**Comment by webdiscus** [comment]
@rohit-gohri 

## Description of the problem

If HMR is enabled in `serv` mode, Webpack injects over `260 KB`  JS code  into all JS scripts.
So the plugin checks whether the template contains a script and only injects an empty `hot-update.js` if there are no scripts, to avoid 260KB of unnecessary code.

### How does the plugin detect a script in a template?
The plugin use very simple but very fast parser, w/o RegEx, therefore are resolved the `src` attribute in all detected `script` tags, without regard whether the tag is commented out.

The commented script is resolved too and will be added to the collection.
```html
<!-- <script src="script.js"></script> -->
```

Therefore, the plugin "think" that a script already exists and not add to template.

### Workarounds

1. remove all commented scripts in a template
2. rename the `src` attribute in commended script to other name, e.g. `data-src`
    ```html
     <!-- <script data-src="script.js"></script> -->
     ```

### Compromise

Remove the condition `Collection.hasScript()`, then the empty script will be injected into a template always (if hot is enabled), that is not optimal.

Add a check to see if the script is commented out, I definitely won't do this, because this will kill performance.

### What compromise would you choose?
1. just rename the attribute in the commented out script (non-obvious solution)
2. you suggestion: always (if hot is true) inject the `hot-update.js` into a template, without regard whether a script already exists (not optimal, load additional 260 KB if a template already contains a script)

**Comment by rohit-gohri** [comment]
Actually I have another case without any commented out `script` tags too that is not getting injected with the script too. I think there is another issue with detection of script, I will post an example soon.

**Comment by webdiscus** [comment]
@rohit-gohri 

I have updated the plugin to `1.7.2`. Here is injected the `hot-update.js` always when `devServer.hot = true`.

**Comment by rohit-gohri** [comment]
That fixes my problem! Thanks!
