### ISSUE TITLE
[FEATURE REQUEST] Handlebars: precompile template with partials

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/html-bundler-webpack-plugin#126]
### Discussed in https://github.com/webdiscus/html-bundler-webpack-plugin/discussions/124

<div type='discussions-op-text'>

<sup>Originally posted by **Bessonov** December  4, 2024</sup>
Hello everyone,  

I’m a bit stuck and not sure if the issue lies with me, Handlebars, or the bundler. Essentially, I’m trying to replicate [this example](https://handlebarsjs.com/examples/partials/inline-blocks.html):
https://github.com/Bessonov/handlebars-inheritance.

However, when I run:  
```sh  
npm install  
npm start  
```  

I get the following output:  
```
start  
test outside  
end  
```  

Instead of something like:  
```html  
start  
test outside  
<div class="nav">  
  My Nav test navtest layout  
</div>  
<div class="content">  
  My Content  
</div>  
end  
```  

In the (server-side) project, I’m using Webpack’s `entry`, but even when I use the [plugin's entry](https://github.com/Bessonov/handlebars-inheritance/blob/main/webpack.config.mjs#L5), it doesn’t work either.

If I debug the project, I notice [here](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/master/src/Loader/Preprocessors/Handlebars/index.js#L216) that the Handlebars instance contains partials and additional helpers. However, it seems they aren't being compiled into the output.

What am I doing wrong?

BTW, no success with [handlebars-layouts](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/master/test/cases/_preprocessor/handlebars-helper-layouts/webpack.config.js#L41) too.</div>

**Comment by vralle** [comment]
A small experiment.
Move data to config and change endpoint to hbs.
```js
new HtmlBundlerPlugin({
      ...usePluginEntry ? {
        entry: {
          index: {
            import: './src/index.hbs',
          },
        },
      } : {},
      preprocessor: 'handlebars',
      data: {
        outsideText: 'test outside',
        navText: 'test nav',
        layoutText: 'test layout',
      },
      preprocessorOptions: {
        partials: [
          `./src/partials`,
        ],
      },
    }),
```
Compile it and now result `dist/index.html`
Code:
```
start
test outside
<div class="nav">
      My Nav test nav
test layout
</div>
<div class="content">
      My Content
</div>end
```

**Comment by webdiscus** [comment]
> There is a theory that it is a matter of import usage. Where do you want to intercept the import of `index.hbs`, compile it with arguments and pass the result to the index.mjs?

The goal is to compile a `*.hbs` template into  `template function` that is callable in the browser with arguments in runtime.

I have just implemented this very useful feature. I'm already by testing.

**Comment by vralle** [comment]
If we are talking about the plugin as a static generator, then everything already works. For dynamics, I would prefer React or Vue)

**Comment by webdiscus** [comment]
Hallo @Bessonov,

I have Implemented the compilation of sub partials in `compile` mode, see the [test case](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/_preprocessor/js-tmpl-hbs-compile-partials).

Try please new version `4.7.0`.

**Comment by Bessonov** [comment]
@webdiscus Thank you so much! I truly appreciate your time and effort. I’m back from work now and will try it out in a few hours!

**Comment by Bessonov** [comment]
@webdiscus Amazing, thanks, it works! I don't use helpers now, but I could imagine using some helpers like equal comparison in the future. At work, we use some helpers (eq, coalesce, etc.) with handlebars-loader.

Just to give a little more context, Handlebars is used exclusively on the backend for:
- Generating HTML emails.
- Generating SQL migrations (primarily to have up/down scripts in the same file, e.g.: `{{#if up}}CREATE ...{{/if}}{{#if down}}DROP ...{{/if}}`).
- Generating latex files.

In all cases, it's just about importing templates (with extensions like .hbs, but also .sql and .tex) and passing variables to get the generated string. So no index.hbs/index.html or similar is involved.

However, I have noticed that the filesystem cache doesn't pick up changes in the parent template. I am OK with that; I just need to remember to delete the cache. Also, it would be nice if an error were thrown when a partial wasn't found.

**Comment by webdiscus** [comment]
@Bessonov 

> Also, it would be nice if an error were thrown when a partial/variable/etc. wasn't found. Just to avoid mistakes.

1. if in a partial used undefined variable, e.g. `<div>Person: {{ undefined_var }}</div>`, then will be rendered to `<div>Person:</div>`. It's ok. Handlebars generates no warnings. The plugin can't do such checking, this should do Handlebars compiler.

3. if in a template used wrong name of a partial, e.g. `<footer>{{> footer_wrong_name}}</footer>`, then:
    - in `render` mode will be displayed Error in console: `The partial "footer_wrong_name" could not be found`. Already works.
    - in `compile` mode, the partial will be checked in runtime in browser at execution of generated `template function` and will be output in Browser Console the ERROR: `message: "... The partial "footer_wrong_name" could not be found", ...`
      The plugin can't check the partial name at compilation on server, because Handlebars generates a string code and the Exception works only in runtime. Also, it's impossible to check it on server side in the plugin.

**Comment by webdiscus** [comment]
> In all cases, it's just about importing templates (with extensions like .hbs, but also .sql and .tex) and passing variables to get the generated string. So no index.hbs/index.html or similar is involved.

You can generate static HTML with passing variables into the template using the [entry data](https://github.com/webdiscus/html-bundler-webpack-plugin#option-entry-data) option. 

For example, there is the `home.hbs` template with variables:
```html
<h1>{{ title }}<h1>
<div>Person: {{name}}, {{age}}</div>
```

Add to the `entry` option the `data` option as an object:
```js
new HtmlBundlerPlugin({
  entry: [
    {
      import: 'src/views/home.hbsl', 
      filename: 'index.html',
      data: {
         // pass variables into the concrete template
         name: 'Max',
         age: 31,
      },
    },
  ],
  data: {
    // pass data into all entries
    title: 'My Title',
    ...
  },
}),
```

If you have dynamic data, e.g. from DB, then you can define the [`data`](https://github.com/webdiscus/html-bundler-webpack-plugin#data) option as path to the JSON or JS file.

Add to the `entry` option the `data` option as the path to the JS file:
```js
new HtmlBundlerPlugin({
  entry: [
    {
      import: 'src/views/home.hbs', 
      filename: 'index.html',
      data: 'src/data/home.js', // <= the exported data in JS will be automatically passed into template
    },
  ],
  data: 'src/data/commonData.js',
}),
```

The `src/data/home.js`:

```js
// here you can load the data from DB
const data = {
  "name": "Max",
  "age": "31",
};

module.exports = data;
```

See please the test case [option-entry-data-file](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/option-entry-data-file).

**Comment by Bessonov** [comment]
> Handlebars generates no warnings. The plugin can't do such checking, this should do Handlebars compiler.

Yes, and handlebars has [`strict` mode](https://handlebarsjs.com/api-reference/compilation.html#handlebars-compile-template-options) for that. And great thing, options are now passed to `precompile` (this wan't the case before the change), and now I can use just: 
```js
		new HtmlBundlerPlugin({
			preprocessor: 'handlebars',
			preprocessorOptions: {
				strict: true, // <-- here
				partials: [
					`./src/backend/newsletter/templates/layouts`,
				],
			},
		}),
```

One thing I am unsure about the [implementation](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/0a9833ebaa6028a95aff8c14c8a4e3fedad5a509/src/Loader/Preprocessors/Handlebars/index.js#L214), is, that the ordering of partials used and compiled could be important. May be you can offload the work to handlebars itself: https://stackoverflow.com/questions/40445476/getting-a-list-of-partials-actually-used-in-handlebars-template-compile/61131228#61131228 . 

> You can generate static HTML with passing variables into the template using the entry data option.

Thanks, yes, I saw it in the documentation. However, I am not sure I can use that, because I don't store the generated files. For example, in the latex generation scenario, I get a mix of user input and data from the database, I generate latex file in memory and pass it as body to pdf generation service, which returns an ID of pdf file. Also I don't see benefits to use it for the newsletter. However, I think it could be used for a blog, where the data is static.

Basically, my entry point isn't a html or template file, but a server file with `http.createServer`.















> Handlebars generates no warnings. The plugin can't do such checking, this should do Handlebars compiler.

Yes, and Handlebars has [`strict` mode](https://handlebarsjs.com/api-reference/compilation.html#handlebars-compile-template-options) for that. And the great thing is, options are now passed to `precompile` (this wasn’t the case before the change), so now I can just use it: 
```js
		new HtmlBundlerPlugin({
			preprocessor: 'handlebars',
			preprocessorOptions: {
				strict: true, // <-- here
				partials: [
					`./src/backend/newsletter/templates/layouts`,
				],
			},
		}),
```

One thing I’m unsure about in the [implementation](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/0a9833ebaa6028a95aff8c14c8a4e3fedad5a509/src/Loader/Preprocessors/Handlebars/index.js#L214) is whether the ordering of partials used and compiled could be important. Maybe you can offload this work to Handlebars itself: https://stackoverflow.com/questions/40445476/getting-a-list-of-partials-actually-used-in-handlebars-template-compile/61131228#61131228. 

> You can generate static HTML with passing variables into the template using the entry data option.

Thanks, yes, I saw it in the documentation. However, I’m not sure I can use that because I don’t store the generated files. For example, in the LaTeX generation scenario, I get a mix of user input and data from the database, I generate a LaTeX file in memory, and pass it as the body to a PDF generation service, which returns an ID of the PDF file. Also, I don’t see benefits in using it for the newsletter. However, I think it could be used for a blog, where the data is static.

Basically, my entry point isn’t an HTML or template file but a server file with `http.createServer`, which is packages into single file by webpack.

**Comment by webdiscus** [comment]
> One thing I am unsure about the [implementation](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/0a9833ebaa6028a95aff8c14c8a4e3fedad5a509/src/Loader/Preprocessors/Handlebars/index.js#L214), is, that the ordering of partials used and compiled could be important. 

The  implementation of the `compile` method is correct. This is used to compile the template imported in JS with all partials using the `Handlebars.precompile` method. This method generate always pure string containing template function (JavaScript) with will be parsed and executed in browser only.

> May be you can offload the work to handlebars itself: https://stackoverflow.com/questions/40445476/getting-a-list-of-partials-actually-used-in-handlebars-template-compile/61131228#61131228 .

The module already do it [here](https://github.com/webdiscus/html-bundler-webpack-plugin/blob/0a9833ebaa6028a95aff8c14c8a4e3fedad5a509/src/Loader/Preprocessors/Handlebars/index.js#L115).

**Comment by webdiscus** [comment]
@Bessonov 

What other problems have you noticed?

- the filesystem cache doesn't pick up changes in the parent template

Is  the "precompile template with partials" issue solved? Then I can close this issue.
For other issues create please separate ticket.

**Comment by Bessonov** [comment]
I see another caching issue: https://github.com/Bessonov/handlebars-inheritance/commit/1f0c87fecdc290f4c914956faad6619498e1a5bc

Basically, templates:
```handlebars
// layout / parent
{{#if a}}a{{/if}}
{{#if b}}b{{/if}}

// child
{{#> layout}}
{{/layout}}
```
```js
index({ a: true }) // outputs as expected "a"
index({ b: true }) // second call outputs "a b"
```

**Comment by vralle** [comment]
> Thanks, yes, I saw it in the documentation. However, I’m not sure I can use that because I don’t store the generated files. For example, in the LaTeX generation scenario, I get a mix of user input and data from the database, I generate a LaTeX file in memory, and pass it as the body to a PDF generation service, which returns an ID of the PDF file. Also, I don’t see benefits in using it for the newsletter. However, I think it could be used for a blog, where the data is static.

> Basically, my entry point isn’t an HTML or template file but a server file with , which is packages into single file by webpack.http.createServer

A very interesting strategy of using a server where static assets like html, styles and images are stored only in memory. Not much context, but it may seem that after email there is no local copy of what was sent)

But I'm wondering about something else. If the endpoint is JS, then it might be more convenient to import the static code and configure handlebars.js directly. It seemed to me that the handlebars.js configuration could fit in a few lines. And we'd get declarative code, instead of trying to use a static generator in a non-standard way.

**Comment by Bessonov** [comment]
> If the endpoint is JS, then it might be more convenient to import the static code and configure handlebars.js directly. It seemed to me that the handlebars.js configuration could fit in a few lines.

Maybe you're right. In fact, I used Pug this way many years ago. But then I switched to packaging the server side with webpack, creating a self-contained file with built-in migrations, templates, and more. The main drivers were:  
- **Size:** I get a `server.js` file of just a few MBs, which I can run on a Node.js runtime instead of dealing with nearly 1 GB of node modules.
- **Convenience:** I don't need to ensure that migrations, templates, OpenAPI yaml schemas, and other resources are in the right place. I don't need to use `fs/send` for them.

> And we'd get declarative code, instead of trying to use a static generator in a non-standard way.

From my point of view, the compile mode is exactly suited for dynamic use cases. To be honest, I highly underestimated the complexity behind it. For a moment, I even considered getting rid of loaders and doing it the old way. Maybe that's the solution :shrug:

**Comment by vralle** [comment]
@Bessonov, have you tried [handlebars-loader](https://github.com/pcardune/handlebars-loader)?

**Comment by Bessonov** [comment]
@vralle Yes, and in fact, this is exactly what I am (still) using for database migrations. Overall, I am quite happy with it; however, it doesn't support handlebars' inheritance, which is very useful for html-emails and dynamic templates. This was the trigger for me to explore other loaders/plugins.
