### ISSUE TITLE
[QA] How to include html partials

### ISSUE THREAD

**Issue by CangyuanLi** [webdiscus/html-bundler-webpack-plugin#131]
## Question

**What is motivation or use case for adding/changing the behavior?**

Hi, thanks for the awesome tool! I need to produce self-contained HTML files due to regulatory reasons, and my current barriers are internal referenced html files. Would it be possible to inline referenced html files as well as CSS and JS? For example, currently, given an index.html like this:

```html
<!DOCTYPE html>
<html>
<body>
    <a href="other.html">Go to other page</a>
</body>
</html>
```

and other.html like this:

```html
<!DOCTYPE html>
<html>
<body>
    Hello World
</body>
</html>
```

and the default inliner config.js described in the README:

```js
const path = require('path');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = {
  mode: 'production',
  output: {
    path: path.join(__dirname, 'dist/'),
  },
  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        index: './index.html',
      },
      css: {
        inline: true, // inline CSS into HTML
      },
      js: {
        inline: true, // inline JS into HTML
      },
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader'],
      },
      // inline all assets: images, svg, fonts
      {
        test: /\.(png|jpe?g|webp|svg|woff2?)$/i,
        type: 'asset/inline',
      },
    ],
  },
  performance: false, // disable warning max size
};
```

nothing happens, and the link to `other.html` becomes broken.

**Describe the solution you'd like**

I would love to be able to specify something like 
```js
html: {inline: true}
```

to inline the other html files into the entry.

**Describe alternatives you've considered**

I am not that experienced with JS (these files are the output of https://jupyterbook.org/en/stable/intro.html), so apologies if I have missed an easy workaround!

## Appreciation for the useful project

- [ ] After the feature is implemented, do not forget to give a star ⭐

**Comment by webdiscus** [comment]
Hello @CangyuanLi,

what do you means "inline referenced html files as well as CSS"?

1. Inject the content of the referenced HTML file `<a href="other.html">Go to other page</a> into paren HTML`?
   If yes, then you should use any template engine to include the HTML partials into parent file.
2. You wish to resolve referenced HTML file `<a href="src/views/other.html">Go to other page</a>, that the `other.html` will be automatically rendered as an entrypoint into separate file and original source reference will be replaced with output URL, e.g. as `<a href="pages/other.html">Go to other page</a>, where `pages/other.html` is the public path, relative to `dist/` directory.

Can you please describe what you have and what you wish as result, please with concrete example.

The 2nd point is very interesting. I have the same idea since 2 years. But it's very complex to implement. Firsts I need define a concept, how it should be work.

**Comment by CangyuanLi** [comment]
> Hello @CangyuanLi,
> 
> what do you mean "inline referenced html files as well as CSS"?
> 
>     1. Inject the content of the referenced HTML file `<a href="other.html">Go to other page</a>` into parent HTML file?
>        If yes, then you should use any template engine to include the HTML partials into parent file.
> 
>     2. You wish to resolve referenced HTML file `<a href="src/views/other.html">Go to other page</a>`, that the `other.html` will be automatically rendered as an entrypoint into separate file and original source reference will be replaced with output URL, e.g. as `<a href="pages/other.html">Go to other page</a>`, where `pages/other.html` is the public path, relative to `dist/` directory.
> 
> 
> Can you please describe what you have and what you wish as result, please with concrete example.
> 
> The 2nd point is very interesting. I have the same idea since 2 years. But it's very complex to implement. Firsts I need define a concept, how it should be work.

Thank you! Number 1 is what I need. I will try to come up with a more concrete example.

**Comment by webdiscus** [comment]
@CangyuanLi 

The bundler plugin supports most popular [template engines](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/131#template-engine), defaults is [Eta](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/131#using-template-eta). Please read the [documentation](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/131#template-engine).

To include an HTML partial into the parent, just use template syntax:
```html
<!DOCTYPE html>
<html>
<body>
    <%~ include('/src/views/partials/other.html') %>
</body>
</html>
```

The _src/views/partials/other.html_ parial should not contain the `html` `head` `body` tags, because your parent `index.html` file already contains ones.
```html
<h1>Hello World</h1>
```

The generated output HTML:
```html
<!DOCTYPE html>
<html>
<body>
    <h1>Hello World</h1>
</body>
</html>
```

P.S. Please create a small repo with your HTML files and I can help you.

**Comment by CangyuanLi** [comment]
> @CangyuanLi 
> 
> 
> 
> is your problem solved?

Yes, thank you so much for the detailed answer!!
