### ISSUE TITLE
Runtime error when using react-markdown and JavaScript is inlined

### ISSUE THREAD

**Issue by hqw567** [webdiscus/html-bundler-webpack-plugin#23]
## Current behaviour

When using React Markdown when JavaScript is inlined, webpack parsing error

### Reproduction Example

https://github.com/hqw567/html-bundler-webpack-plugin-react.git

## Environment

- OS: Windows
- version of Node.js: v18.16.0
- version of Webpack: v5.88.1
- version of the Plugin: v2.0.1

## Additional context
![image](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/74847198/930469ce-1958-437e-a0de-620ab86db27c)
![image](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/74847198/79914885-b8f9-4ede-a99a-c92f0d2742a7)

**Comment by webdiscus** [comment]
@hqw567 

Thanks for the issue,
I will fix it.

**Comment by webdiscus** [comment]
# Issue

When used the `react-markdown` module in the `development` mode, the Webpack generate JS code from the source code containing comments. The `react-markdown` module contains `invalid inline-JS` comments, e.g.:

```js
/**
 * DOM clobbering is this:
 * ...
 * <script>alert(x) // `x` now refers to the DOM `p#x` element</script>
 */
```

This comment is valid in a JS file, but not in `inline-JS`, 
because the inline-JS code is already inside the `<script>...</script>` tag.

The generated HTML with inlined source JS code including `invalid` comment:
```js
<html>
<head>
</head>
<body>

  <script>
    /**
    * DOM clobbering is this:
    * ...
    * <script>alert(x) // `x` now refers to the DOM `p#x` element</script>
    */
    // JavaScript code ...
  </script>

</body>
</html>
```

The `<script>...</script>` in JS-comment breaks the HTML.

# Workarounds:

1. When you get this issue, don't use the `js.inline` option as `'auto'` or `true` in `development` mode for such `inline-unsave` JS modules.


2. If you want to inline JS code, use the `production` mode by `wepack serve/watch` to remove all `unsave` comments in inlined JS code:

_package.json_
```js
"scripts": {
   "start": "webpack serve --mode development",
   "start:prod": "webpack serve --mode production", <-- use production mode
   "watch": "webpack watch --mode development",
   "build": "webpack --mode=production --progress"
},
```

_webpack.config.js_

```js
module.exports = {
  mode: 'production',
  // ...
}
```

# TODO

## Idea

Add the new `js.inlineOptions` option.

In this option will be available the possibility to remove comments from inlined JS code, e.g.:

```js
new HtmlBundlerPlugin({
  entry: {
    index: './src/views/index.html',
  },

  js: {
    filename: 'js/[name].[contenthash:8].js',
    inline: true, // or 'auto'
    inlineOptions: {
      removeComments: true, // remove all comments from inlined JS code to avoid parsing errors
    },
  },

  //verbose: true,
}),
```

## Penalty
If you use `sourceMap` for JS code, it will not work, because the `sourceMap` is generated before we remove comments.
It means, the `sourceMap` will be invalid.
For performance reason, I don't want to recalculate the `sourceMap` for modified inlined JS-code.


# P.S.
For performance reason, I don't see a sense automatically to convert HTML reserved chars in comments of inlined JS code for a very very rare case.

Using only `react` and `react-markdown`, the Webpack generate 2.5 MB code in `development` mode.  If we replace all HTML-chars in JS, this will drastic decrease performance in `development` mode.

**Comment by hqw567** [comment]
@webdiscus  

Thank you very much for providing the solution. However, I have encountered another minor issue 😶‍🌫️. I am unable to use comments in the SCSS file; I have to remove all comments to compile it successfully.

![image](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/74847198/6d34c6ed-43f6-4ff6-b777-54aa959fb6cd)

**Comment by hqw567** [comment]
> @webdiscus
> 
> Thank you very much for providing the solution. However, I have encountered another minor issue 😶‍🌫️. I am unable to use comments in the SCSS file; I have to remove all comments to compile it successfully.
> 
> ```js
> // Webpack Loader
> {
>         test: /\.(css|sass|scss)$/,
>         use: ['css-loader', 'sass-loader', 'postcss-loader'],
>  }
> ```
> 
> ![image](https://user-images.githubusercontent.com/74847198/251090125-6d34c6ed-43f6-4ff6-b777-54aa959fb6cd.png)

I have identified the issue. It is due to the order of execution of Webpack loaders. The correct order should be sass-loader => postcss-loader => css-loader.

So, the configuration should be as follows:
```js
// Webpack Loader
{
    test: /\.(css|sass|scss)$/,
    use: ['css-loader', 'postcss-loader', 'sass-loader']
}
```

Thank you once again for your assistance.
