### ISSUE TITLE
[FEATURE REQUEST] Watch handlebars helpers for changes

### ISSUE THREAD

**Issue by 5ulo** [webdiscus/html-bundler-webpack-plugin#25]
## Current behaviour

Changes made to handlebars helper *.js are not compiled. Page reloads on helper save, but the changes are not compmilet back to the output. As for now the solution is to restart `npm run start`. Also adding/renaming/deleting helper file does not made any changes.

## Expected behaviour

Changes should be compiled to the code.

### Reproduction Example

```js
loaderOptions: {
    preprocessor: 'handlebars',
    preprocessorOptions: {
        root: path.join(PATH_PAGES),
        views: [
            PATH_PARTIALS
        ],
        partials: [
            PATH_PARTIALS
        ],
        helpers: [
            PATH_HELPERS
        ]
    },
},
```
helpers are in project root `helpers/*.js`

## Environment

- OS: [macOS, Linux, Windows]
- version of Node.js: v18.16.0
- version of Webpack: 5.88.2
- version of the Plugin: 2.7.0

## Additional context

Thank you

**Comment by webdiscus** [comment]
Hello @5ulo,

thanks for reporting the issue. I will try to fix it.

**Comment by webdiscus** [comment]
@5ulo try the new version `2.8.0`.
You can add/remove/rename/change a helper in the helper's directory.

One limitation: by add/remove/rename of a helper file, the template will new compiled, but the browser will not be live reloaded.

This seems to be a bug in the Webpack HMR code, because the hot update code says in the browser console:
```
[HMR] Checking for updates on the server... [log.js:39:12](webpack:///node_modules/webpack/hot/log.js?)
[HMR] Nothing hot updated. [log.js:39:12](webpack:///node_modules/webpack/hot/log.js?)
[HMR] App is up to date.
```
You should reload your browser manually.
I don'k know how to fix it :-/

**Comment by 5ulo** [comment]
Manual reload on create/remove/rename is the least.. HMR on content change works with the `2.8.0`. Good job
