### ISSUE TITLE
Favicon plugin causes a crash if no link is included

### ISSUE THREAD

**Issue by GingerIndustries** [webdiscus/html-bundler-webpack-plugin#64]
## Current behaviour

If the HTML file does not include a `<link rel="icon">` tag and the `FaviconBundlerPlugin` is enabled, webpack crashes with the following traceback:
```
  throw new Error('Tap function (tapPromise) did not return promise (returned ' + _promise1 + ')');
        ^

Error: Tap function (tapPromise) did not return promise (returned undefined)
    at _next0 (eval at create (/home/ginger/vyxal.github.io/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:9)
    at eval (eval at create (/home/ginger/vyxal.github.io/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Expected behaviour

The plugin should probably throw an error explaining that the file lacks a `link` tag.

### Reproduction Example

Create an HTML file without a `<link rel="icon">` tag, enable the `FaviconBundlerPlugin`, and attempt to bundle it with the `HtmlBundlerWebpackPlugin`.

## Environment

- OS: Linux
- version of Node.js: v18.13.0
- version of Webpack: 5.89.0
- version of the Plugin: 3.4.0

**Comment by webdiscus** [comment]
Hello @GingerIndustries,

thank you for the issue report.
I wil fix it.

**Comment by webdiscus** [comment]
it is a really special use case `<link rel="icon">` or it's an user error? Should be this tag ignored or should an exception occur?

**Comment by GingerIndustries** [comment]
> it is a really special use case `<link rel="icon">` or it's an user error? Should be this tag ignored or should an exception occur?

I'm of the opinion that if the plugin is enabled but the page lacks a favicon it's an error, since why would they have the plugin if they didn't have a favicon to use it with?

**Comment by webdiscus** [comment]
> I'm of the opinion that if the plugin is enabled but the page lacks a favicon it's an error, since why would they have the plugin if they didn't have a favicon to use it with?

yes/no

- if the favicon plugin is used but no favicon found, this is an user error, not plugin error. User self should check the generated result and see whether all is correct
- if no favicon was detect, then the  favicon plugin should do nothing, just ignore it, no throw an error, because it brake compilation process (the HTML w/o favicon is valid)
- if in Webpack config are configured CSS, images loaders and no CSS or images was in entry detected, the Webpack throw no exception
- if html-bundler-webpack-plugin is configured with entry as a path to html templates and the entry directory is empty, this is no error too, just will be nothing rendered

All use cases such as `<link rel="icon">` or `<link invalid-href="./favicon.png" rel="icon" />` or the link tag is missing are the same. The plugin doesn't analyse whether any `<link>` tag exists or not in HTML. The plugin detect and resolve only attributes (href, src, etc) by tags. If any resolvable attribute is missing, then plugin do nothing, HTML stay as is.

Also, I will resolve this case (`Favicon file is not found`) w/o an exception.

**Comment by webdiscus** [comment]
But I can display a warning in the console without breaking compilation, for example:

> **Warning**
>
> Favicon file is not found!
> If the `FaviconsBundlerPlugin` is used, at last one favicon source file should be defined, e.g.:
> `<link rel="icon" href="path/to/source/favicon.png">`

**Comment by webdiscus** [comment]
@GingerIndustries 

the crashing is fixed, in this case will be display a warning.
Please check the version `3.4.3`.

**Comment by GingerIndustries** [comment]
Cool, thanks!
