### ISSUE TITLE
Feature request: Give the plugin instance a sensible name

### ISSUE THREAD

**Issue by davidmurdoch** [webdiscus/html-bundler-webpack-plugin#83]
## Feature request

**What is motivation or use case for adding/changing the behavior?**

When debugging webpack configurations it is helpful for plugins to have sensible names. `html-bundler-webpack-plugin` just shows `Plugin`:

<img width="345" alt="image" src="https://github.com/webdiscus/html-bundler-webpack-plugin/assets/187813/d969bfb2-4d15-48e4-97b4-b75828af604e">

**Describe the solution you'd like**

Give the plugin instance a name that describes what it is, like `HtmlBundlerWebpackPlugin`.

This sort of thing could be considered breaking change, but if you are going to rename the library soon it'd be a great time to introduce this kind of change.

**Comment by webdiscus** [comment]
Hello @davidmurdoch,

thanks for the constructive suggestion.
The instance was named as `HtmlBundlerPlugin` in the version `3.6.5`.

### P.S.

I don't plan to rename it soon, while the plugin is still not popular.
The purpose of renaming is to distance ourselves from the `html-webpack-plugin` so that the `html-bundler-webpack-plugin` is not confused with `html-webpack-plugin`. The name is similar, but has absolutely  other meaning.
